import { subscribe, pushTo, takeAlert, hashEndpoint } from '../src/push.js';
const c = globalThis.crypto;
const k = await c.subtle.generateKey({ name: 'ECDSA', namedCurve: 'P-256' }, true, ['sign', 'verify']);
const jwk = JSON.stringify(await c.subtle.exportKey('jwk', k.privateKey));
const pubRaw = Buffer.from(await c.subtle.exportKey('raw', k.publicKey)).toString('base64url');
const mem = new Map();
const stub = { get: async (x) => mem.get(x) ?? null, put: async (x, v) => void mem.set(x, v), del: async (x) => void mem.delete(x), acquire: async () => true, release: async () => {} };
const env = { STORE: { idFromName: () => 'x', get: () => stub }, VAPID_PRIVATE_JWK: jwk, VAPID_PUBLIC: pubRaw };
const seen = [];
globalThis.fetch = async (url, init) => { seen.push({ url, init }); return new Response(null, { status: 201 }); };
await subscribe(env, { id: 7, role: 'rc', name: 'Test RC', region: 'TANGA' }, { endpoint: 'https://fcm.googleapis.com/fcm/send/abc123' });
const r = await pushTo(env, (w) => w.region === 'TANGA', { title: 'Hello', body: 'World', url: '/' });
console.log('push result', JSON.stringify(r));
const auth = seen[0].init.headers.Authorization;
const m = /^vapid t=([^,]+), k=(.+)$/.exec(auth);
const [h, p, s] = m[1].split('.');
const ok = await c.subtle.verify({ name: 'ECDSA', hash: 'SHA-256' }, k.publicKey, Buffer.from(s, 'base64url'), new TextEncoder().encode(`${h}.${p}`));
console.log('endpoint called:', seen[0].url, '| JWT signature valid:', ok, '| aud:', JSON.parse(Buffer.from(p, 'base64url')).aud, '| key matches:', m[2] === pubRaw, '| content-length:', seen[0].init.headers['Content-Length']);
const hsh = await hashEndpoint('https://fcm.googleapis.com/fcm/send/abc123');
console.log('alert for that device:', JSON.stringify(await takeAlert(env, hsh)));
console.log('second fetch (queue empty):', JSON.stringify(await takeAlert(env, hsh)));
